### ISSUE TITLE
Can't submit Transfer Fee or Document

### ISSUE THREAD

**Issue by ithielnor** [Dwolla/dwolla-v2-csharp#16]
@therockstorm The implementation of transfer fees and document uploads looks fine, but neither works. Both return `{"code":"BadRequest","message":"The request body contains bad syntax or is incomplete."}` 

Any ideas?

**Comment by ithielnor** [comment]
I should mention that the document upload I'm testing is here: https://github.com/ithielnor/dwolla-v2-csharp/tree/dev-documents

**Comment by ithielnor** [comment]
@CoolStoryCory clarified that I need to use the customer Id for a transfer fee instead of the funding source. I've submitted #17 with an example of that (which works).

**Comment by therockstorm** [comment]
Got document upload working. Thanks for the starting point, Microsoft doesn't make that easy...
