### ISSUE TITLE
api.nuget still contains the old version 5.1.1.

### ISSUE THREAD

**Issue by Avarie** [Dwolla/dwolla-v2-csharp#32]
Hello, 

could you please publish the 5.2.0 ? 

PM> find-package dwolla.client

Id                                  Versions                                 Description                
--                                  --------                                 -----------                
Dwolla.Client                       {5.1.1}                                  Official C# Wrapper for ...
Time Elapsed: 00:00:00.7842355

Thanks.

**Comment by ShreyaThapa** [comment]
Updated to version 5.2.1 and published to NuGet - https://www.nuget.org/packages/Dwolla.Client/5.2.1
