### ISSUE TITLE
Create Customer vs. Update Customer

### ISSUE THREAD

**Issue by ithielnor** [Dwolla/dwolla-v2-csharp#4]
It looks like [Update Customer](https://docsv2.dwolla.com/#update-a-customer) accepts the same properties as Create Customer (at least for an unverified customer). Should there be a `UpdateCustomerRequest` model or should we just use the `CreateCustomRequest`. If the latter, I suggest renaming it.

**Comment by therockstorm** [comment]
It's actually two separate objects in our backend. We use Scala so for the Update, many of the fields are Option[String] vs String for Create. Additionally, Update can take a Status property for suspending or deactivating a customer. We use Swagger to auto-generate [this page](https://api.dwolla.com/doc) but the generated clients were pretty ugly. I started down the path to auto-generate at least the models from the Swagger JSON, but other things have come up.

**Comment by therockstorm** [comment]
I didn't realize CreateCustomerRequest already has `Status`, it shouldn't. I removed it and created an UpdateCustomerRequest
