### ISSUE TITLE
Remove newtonsoft dependency and use System.Text.Json

### ISSUE THREAD

**Issue by waynebrantley** [Dwolla/dwolla-v2-csharp#41]
This should be a pretty easy transition and would make it such that you have no external dependencies outside of .net.
You currently target standard 1.6, and net core frameworks that use that are depreciated.

Please target for Standard 2.0 and for that target you can use NewtonSoft (#ifdef).
Add targets for NET5.0, NET6.0 and NET7.0.

**Comment by ShreyaThapa** [comment]
Thanks for opening up the issue, @waynebrantley!

This has been released in the latest version - [Dwolla.Client v6.0.0](https://www.nuget.org/packages/Dwolla.Client). Special thanks to @natehitze and @IsaiahDahlberg for their contributions to this release! 👏 🙇‍♀️
